video_set:
  - path: "dataset/mp4/{00000..00009}.tar"
subsamplers:
  - name: ClippingSubsampler
    parameters:
      - oom_clip_count: [5]
        encode_formats: [{"video": "mp4"}]
        min_length: [1]
        max_length: [20]
        precise: [True, False]
  - name: ResolutionSubsampler
    parameters:
      - video_size: [360, 60]
        resize_mode: ["scale"]
  - name: FrameSubsampler
    parameters:
      - frame_rate: [1, 5]
  - name: CutDetectionSubsampler
    parameters:
      - cut_detection_mode: ["all"]
        threshold: [27, 15]
        min_scene_len: [2, 10]
